config/routes.rb
Shig::Application.routes.draw do
  devise_for :users

  root :to => "games#index"

  resources :games do
    resources :persons, :controller => "game_persons"
    resources :twitts, :controller => "game_twitts", :only => [:index]
    
    get :go, :on => :member, :controller => "game_twitts"
    get :who_win, :on => :member, :controller => "game_twitts"
  end
  
  resources :people do
    resources :synonyms, :shallow => true
  end 
end

app/models/synonym.rb
# encoding: utf-8
class Synonym < ActiveRecord::Base
  attr_accessible :name
  
  belongs_to :person
  
  validates :name, :presence => true
  validates :name, uniqueness: { scope: :person_id}
end

app/controllers/synonyms_controller.rb
# encoding: utf-8
class SynonymsController < ApplicationController
  
  #
  # Сообщения об ошибках в шаблонах для разных объектов
  # - edit - для @synonym
  # - new  - для @person
  #
  
  before_filter :find_person, :only => [:new, :create]
  before_filter :find_synonym_and_person, :only => [:edit, :update, :destroy]

  def new
  end
  
  
  #
  # Может, создать синоним, а потом синониму назнасть знаменитость
  # @synonym.person = @person
  # тогда и одинаковые обхекты для сообщения об ошибок будут
  # 
  def create
    @person.synonyms.build(params[:synonym])
    
    if @person.save
      flash[:success] = "Синоним успешно сохранен"
      redirect_to edit_person_path @person
    else
      render :new
    end
  end
  
  def destroy
    @synonym.destroy    

    flash[:success] = "Синоним успешно удален"
    redirect_to edit_person_path(@person)  
  end
  
  def edit
  end
  
  def update
    if @synonym.update_attributes(params[:synonym])
      flash[:success] = "Синоним успешно обновлен"
      redirect_to edit_person_path(@person)
    else
      render :edit
    end
  end
  
  private
    def find_person
      person_id = params[:person_id].to_i
      @person = Person.find(person_id)
    end
    
    def find_synonym_and_person
      id = params[:id].to_i
      @synonym = Synonym.find(id)
      @person = @synonym.person
    end
end

app/views/synonyms/edit.html.erb
<% content_for :page_name do %>
  Редактирование синонима для знаменитости <%= @person.name %>
<% end %>

<%= render :partial => 'shared/error_messages', :locals => { :target => @synonym } %>



<%= form_for @synonym, :url => synonym_path(@synonym), :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render :partial => 'shared/synonym_form', :locals => { :f => f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to edit_person_path(@person), :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Назад
      <% end %>
    	
      <%= button_tag(type: 'submit', class: "btn btn-default") do %>
        <span class="glyphicon glyphicon-ok"></span> Изменить
      <% end %>
    </div>
  </div>
<% end %>

app/views/synonyms/new.html.erb
<% content_for :page_name do %>
  Добавление синонима для знаменитости <%= @person.name %>
<% end %>

<%= render :partial => 'shared/error_messages', :locals => { :target => @person } %>

<%= form_for Synonym.new, :url => person_synonyms_path(@person), :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render :partial => 'shared/synonym_form', :locals => { :f => f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to edit_person_path(@person), :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Назад
      <% end %>

      <%= button_tag(type: 'submit', class: "btn btn-default") do %>
        <span class="glyphicon glyphicon-ok"></span> Создать
      <% end %>
    </div>
  </div>
<% end %>