config/routes.rb
Shig::Application.routes.draw do
  devise_for :users

  root :to => "games#index"

  resources :games do
    resources :persons, :controller => "game_persons"
    resources :twitts, :controller => "game_twitts", :only => [:index]
    
    get :go, :on => :member, :controller => "game_twitts"
    get :who_win, :on => :member, :controller => "game_twitts"
  end
  
  resources :people do
    resources :synonyms, :shallow => true
  end 
end

app/views/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div class="alert alert-danger">
    <p>Не удается произвести сохнанение. Созникли следующими проблемы</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if game %>
  <div class="list-group">
    <%= link_to 'Игра', edit_game_path(game), :class => "list-group-item" %>
    <%= link_to 'Знаменитости', game_persons_path(game), :class => "list-group-item" %>
    <%= link_to 'Твитты',  game_twitts_path(game), :class => "list-group-item" %>
  </div>
<% end %>

app/views/shared/_person_form.html.erb
<% if @game%>
  <%= hidden_field_tag :game_id, @game.id %>
<% end %>
<div class="form-group">
  <%= f.label :name, "Знаменитость", :class => "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>

app/views/shared/_synonym_form.html.erb
<div class="form-group">
  <%= f.label :name, "Синоним:", :class => "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>

app/views/shared/_synonym_index.html.erb
<div class="row">
	<div class="col-md-4">
		<h3>Синонимы</h3>		
	</div>
	<div class="col-md-4 col-md-offset-4">
		<%= link_to person.nil? ? "#" : new_person_synonym_path(person), :class => "btn btn-success #{person.nil? ? 'disabled' : ''}" do %>
			<span class="glyphicon glyphicon-plus"></span> Создать новый
		<% end %>
	</div>
</div>
<% if person %>
	<% if person.synonyms.present? %>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Синонимы</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% person.synonyms.each do |synonym| %>
					<tr>
						<td>
							<%= "#{synonym.name}" %>
						</td>
						<td>
							<%= link_to 'Редактировать', edit_synonym_path(synonym) %>
						</td>
						<td>
							<%= link_to 'Удалить', synonym_path(synonym), method: :delete %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		<p>
			Ни одного синонима еще нет
		</p>
	<% end %>
<% else %>
	Что бы добавить синоним - сначала создайте знаменитость
<% end %>