config/routes.rb
Shig::Application.routes.draw do
  devise_for :users

  root :to => "games#index"

  resources :games do
    resources :persons, :controller => "game_persons"
    resources :twitts, :controller => "game_twitts", :only => [:index]
    
    get :go, :on => :member, :controller => "game_twitts"
    get :who_win, :on => :member, :controller => "game_twitts"
  end
  
  resources :people do
    resources :synonyms, :shallow => true
  end 
end

app/models/game_person.rb
class GamePerson < ActiveRecord::Base
  attr_accessible :game, :person
  
  belongs_to :game 
  belongs_to :person
  
  validates :person_id, uniqueness: { scope: :game_id}
end

app/controllers/game_persons_controller.rb
# encoding: utf-8
class GamePersonsController < ApplicationController
  #layout "game_layout"
  before_filter :find_game, :only => [:index, :new, :create, :destroy]
  
  def index
    index_init
  end
  
  def new
  end

  def create
=begin
    person = Person.find_by_id(params[:person].to_i)

    if person
      @game.people << person

      flash[:success] = "Знаменитость успешно добавлена"
    else
      flash[:error] = "Знаменитость не найдена"
    end
    
    redirect_to game_persons_path(@game)
    #render :index
=end
    person = Person.find_by_id(params[:person].to_i)

    if person
      @game_person = GamePerson.new(:game => @game, :person => person)
      if @game_person.save
        flash[:success] = "Знаменитость успешно добавлена"
        redirect_to game_persons_path(@game)
      else
        index_init
        render :index
      end
    else
      flash[:alert] = "Знаменитость не найдена"
      redirect_to game_persons_path(@game)
    end
  end

=begin
  #
  # todo
  # Подумать о возможности как-то использовать часть экшена create контроллера PeopleController
  def create
   
    # todo: тут проверить существует ли уже добавляемая персона. если да, то подставить ее id иначе:
    name = params[:person][:name].to_s
    
    if name.present?
      person = Person.new
      person.name = params[:person][:name]
      person.save
      
      @game.people << person
      @people = @game.people      
    else
      #todo тут или поругать или на модель понадеяться  
    end    
    
    puts "render :index"
    render :index
  end
=end
  
  def destroy
    id = params[:id].to_i

    person = Person.find(id)
    
    @game.people.delete person
    
    redirect_to game_persons_path(@game)
  end
  
  private
  
    # todo
    # отругать, если game_id - не число
    def find_game
      game_id = params[:game_id].to_i
      @game = Game.find(game_id)
    end
    
    def index_init
      @people = @game.people
      @all_people = Person.all(:order => :name)   
    end
end

app/views/game_persons/_person_select.html.erb
<div class="row">
  <%= form_for @game, :url => game_persons_path(@game), :method => :post, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
    <div class="form-group">
      <%= label_tag :person, "Знаменитость", :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= select_tag :person, options_from_collection_for_select(@all_people, "id", "name"), :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit "Добавить", :class => "btn btn-default"%>
      </div>
    </div>
  <% end %>
</div>

app/views/game_persons/index.html.erb
<% content_for :left_nav do%>
  <%= render :partial => 'shared/navbar', :locals => { :game => @game } %>
<% end %>

<%= content_for :page_name do %>
	Знаменитости
<% end %>

<%= content_for :page_actions do %>
	<%= link_to new_game_person_path(@game) , :class => "btn btn-success" do %>
		<span class="glyphicon glyphicon-plus"></span> Создать новую знаменитость
	<% end %>
<% end %>


<%= render :partial => 'shared/error_messages', :locals => { :target => @game_person } %>


<%= render :partial => 'person_select', :locals => { :game_person => @game} %>

<% if @people.present? %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Знаменитости</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @people.each do |person| %>
				<tr>
					<td>
						<%= "#{person.name}" %>
					</td>
					<td>
						<%= link_to 'Редактировать', edit_person_path(person, :game_id => @game.id) %>
					</td>
					<td>
						<%= link_to 'Удалить', [@game, person], method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>
		Ни одной знаменитости еще нет
	</p>
<% end %>

app/views/game_persons/new.html.erb
<% content_for :left_nav do%>
  <%= render :partial => 'shared/navbar', :locals => { :game => @game } %>
<% end %>

<%= form_for Person.new, :as => :person, :url => game_persons_path(@game), :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render :partial => 'shared/person_form', :locals => { :f => f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Создать", :class => "btn btn-default"%>
    </div>
  </div>
<% end %>

<h3>Синонимы</h3>
Еще нет ни одного синонима. <%#= link_to 'Добавить синоним', new_game_person_path(@game) %>