config/routes.rb
Shig::Application.routes.draw do
  devise_for :users

  root :to => "games#index"

  resources :games do
    resources :persons, :controller => "game_persons"
    resources :twitts, :controller => "game_twitts", :only => [:index]
    
    get :go, :on => :member, :controller => "game_twitts"
    get :who_win, :on => :member, :controller => "game_twitts"
  end
  
  resources :people do
    resources :synonyms, :shallow => true
  end 
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :date, :timeb, :timee

  has_many :twitts

  has_many :game_person
  has_many :people, through: :game_person
  
  before_save :convert_to_datetime
  
  def date
    if @date
      @date
    else
      ddateb.strftime "%d-%m-%Y"
    end 
  end
  
  def timeb
    if @timeb
      @timeb
    else
      ddateb.strftime "%H:%M"
    end
  end
  
  def timee
    if @timee
      @timee
    else
      ddatee.strftime "%H:%M"
    end    
  end
  
  def date= date
    @date = Date.strptime(date, "%d-%m-%Y").strftime("%Y-%m-%d") 
  end
  
  def timeb= time
    @timeb = time #Time.strptime(time, "%H-%M").strftime("%H:%M") 
  end
  
  def timee= time
    @timee = time #Time.strptime(time, "%H-%M").strftime("%H:%M")
  end
  
  def convert_to_datetime
    self.ddateb = DateTime.parse("#{@date} #{@timeb} +04:00")
    self.ddatee = DateTime.parse("#{@date} #{@timee} +04:00")
  end
end

app/controllers/games_controller.rb
# encoding: utf-8
class GamesController < ApplicationController
  #layout "game_layout", :only => :edit
  before_filter :find_game, :only => [:edit, :update, :destroy]
  
  def new
    @game = Game.new
    
    #Найдем пятницу текущей недели
    friday = get_friday
    @game.ddateb = Time.zone.parse("#{friday} 18:00").to_datetime
    @game.ddatee = Time.zone.parse("#{friday} 19:00").to_datetime
  end
  
  def create
    @game = Game.new(params[:game])
        
    if @game.save
      flash[:success] = "Игра успешно сохранена"
      redirect_to game_persons_path(@game)
    else
      render :new
    end
  end
  
  def index
    @games = Game.all
  end
  
  def edit
  end
  
  def update
    if @game.update_attributes(params[:game])
      flash[:success] = "Игра успешно обновлена"
      redirect_to games_path
    else
      render :edit
    end
  end
  
  def destroy
    @game.destroy
    
    @games = Game.all
    
    flash[:success] = "Игра успешно удалена"
    redirect_to games_path
  end
  
  private
    def find_game
      game_id = params[:id].to_i
      @game = Game.find(game_id)
    end
  
    def get_friday
      today = Date.today
      today - today.cwday + 5
    end      
end

app/views/games/_form.html.erb
<div class="form-group">
  <%= f.label :date, "Дата", :class => "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :date, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :timeb, "Время начала", :class => "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :timeb, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :timee, "Время конца", :class => "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :timee, :class => "form-control" %>
  </div>
</div>

app/views/games/edit.html.erb
<% content_for :left_nav do%>
  <%= render :partial => 'shared/navbar', :locals => { :game => @game } %>
<% end %>

<% content_for :page_name do %>
  Редактировать игру
<% end %>

<%= render :partial => 'shared/error_messages', :locals => { :target => @game } %>
<%= form_for @game, :url => game_path(@game), :method => :put, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Изменить", :class => "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/games/index.html.erb
<%= content_for :page_name do %>
	Игры
<% end %>

<%= content_for :page_actions do %>
	<%= link_to new_game_path , :class => "btn btn-success" do %>
		<span class="glyphicon glyphicon-plus"></span> Создать новую
	<% end %>
<% end %>

<% if @games.present? %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Дата</th>
				<th>Время начала</th>
				<th>Время конца</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @games.each do |game| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td>
						<%= "#{game.date}" %>
					</td>
					<td>
						<%= "#{game.timeb}" %>
					</td>
					<td>
						<%= "#{game.timee}" %>
					</td>
					<td>
						<%= link_to 'Редактировать', edit_game_path(game) %>
					</td>
					<td>
						<%= link_to 'Удалить', game_path(game), method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>
		Ни одной игры еще нет
	</p>
<% end %>

app/views/games/new.html.erb
<%= render :partial => 'shared/error_messages', :locals => { :target => @game } %>

<% content_for :page_name do %>
  Создать игру
<% end %>


<%= form_for @game, :url => games_path, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Создать", :class => "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/games/show.html.erb
Игры:</br>
<% if @games.present? %>
	<table>
		<thead>
			<tr>
				<th>Дата</th>
				<th>Время начала</th>
				<th>Время конца</th>
			</tr>
		</thead>
		<tbody>
			<% @games.each do |game| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td>
						<%= "#{game.date}" %>
					</td>
					<td>
						<%= "#{game.timeb}" %>
					</td>
					<td>
						<%= "#{game.timee}" %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>
		Ни одной игры еще нет
	</p>
<% end %>